import random
print("Hi, Welcome to the Dice Roller!")
while True:
     print("Press y if you want to roll, n if you want to stop")
     a = str(input())
     if a == "y":
          number = random.choice([1,2,3,4,5,6])
          if number == 1:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |     __       | |")
               print("| |    /  |      | |")
               print("| |    `| |      | |")
               print("| |     | |      | |")
               print("| |    _| |_     | |")
               print("| |   |_____|    | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
          elif number == 2:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |    _____     | |")
               print("| |   / ___ `.   | |")
               print("| |  |_/___) |   | |")
               print("| |   .'____.'   | |")
               print("| |  / /____     | |")
               print("| |  |_______|   | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
          elif number == 3:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |    ______    | |")
               print("| |   / ____ `.  | |")
               print("| |   `'  __) |  | |")
               print("| |   _  |__ '.  | |")
               print("| |  | \____) |  | |")
               print("| |   \______.'  | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
          elif number == 4:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |   _    _     | |")
               print("| |  | |  | |    | |")
               print("| |  | |__| |_   | |")
               print("| |  |____   _|  | |")
               print("| |      _| |_   | |")
               print("| |     |_____|  | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
          elif number == 5:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |   _______    | |")
               print("| |  |  _____|   | |")
               print("| |  | |____     | |")
               print("| |  '_.____''.  | |")
               print("| |  | \____) |  | |")
               print("| |   \______.'  | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
          elif number == 6:
               print(" .----------------. ")
               print("| .--------------. |")
               print("| |    ______    | |")
               print("| |  .' ____ \   | |")
               print("| |  | |____\_|  | |")
               print("| |  | '____`'.  | |")
               print("| |  | (____) |  | |")
               print("| |  '.______.'  | |")
               print("| |              | |")
               print("| '--------------' |")
               print(" '----------------' ")
     elif a == "n":
          break